# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec4440229d275c7b6e23f349698fce01befe8a28af91be856fd27decaa406e823adf74c8ffb1247a81544eaf5181b98c03e7cb063fc1eb3fe3695e06473abd5c

test:
  secret_key_base: ca1109f97ee8063999a1390ce320a9543bf940100d1bcadfa450ecaedaf56864505c563391523c886dd08c839a12d227539c23e3f5228a7e8dbc159e311852ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
